import type { CountryCode, Topic } from "@/lib/types";

export const TOPICS: { id: Topic; label: string }[] = [
  { id: "AI", label: "AI" },
  { id: "Technology", label: "Technology" },
  { id: "Cybersecurity", label: "Cybersecurity" },
  { id: "Climate", label: "Climate" },
  { id: "Environment", label: "Environment" },
  { id: "Energy", label: "Energy" },
  { id: "Business", label: "Business" },
  { id: "Finance", label: "Finance" },
  { id: "Health", label: "Health" },
  { id: "Science", label: "Science" },
  { id: "Politics", label: "Politics" },
  { id: "Sports", label: "Sports" },
  { id: "Entertainment", label: "Entertainment" },
  { id: "Education", label: "Education" }
];

export const COUNTRIES: { id: CountryCode; label: string; region: string }[] = [
  { id: "GLOBAL", label: "Global", region: "World" },
  { id: "US", label: "United States", region: "Americas" },
  { id: "CA", label: "Canada", region: "Americas" },
  { id: "MX", label: "Mexico", region: "Americas" },
  { id: "BR", label: "Brazil", region: "Americas" },
  { id: "AR", label: "Argentina", region: "Americas" },
  { id: "CL", label: "Chile", region: "Americas" },
  { id: "CO", label: "Colombia", region: "Americas" },
  { id: "PE", label: "Peru", region: "Americas" },
  { id: "GB", label: "United Kingdom", region: "Europe" },
  { id: "IE", label: "Ireland", region: "Europe" },
  { id: "FR", label: "France", region: "Europe" },
  { id: "DE", label: "Germany", region: "Europe" },
  { id: "NL", label: "Netherlands", region: "Europe" },
  { id: "BE", label: "Belgium", region: "Europe" },
  { id: "CH", label: "Switzerland", region: "Europe" },
  { id: "AT", label: "Austria", region: "Europe" },
  { id: "IT", label: "Italy", region: "Europe" },
  { id: "ES", label: "Spain", region: "Europe" },
  { id: "PT", label: "Portugal", region: "Europe" },
  { id: "SE", label: "Sweden", region: "Europe" },
  { id: "NO", label: "Norway", region: "Europe" },
  { id: "DK", label: "Denmark", region: "Europe" },
  { id: "FI", label: "Finland", region: "Europe" },
  { id: "PL", label: "Poland", region: "Europe" },
  { id: "CZ", label: "Czech Republic", region: "Europe" },
  { id: "RO", label: "Romania", region: "Europe" },
  { id: "HU", label: "Hungary", region: "Europe" },
  { id: "GR", label: "Greece", region: "Europe" },
  { id: "TR", label: "Turkey", region: "Europe" },
  { id: "RU", label: "Russia", region: "Europe" },
  { id: "UA", label: "Ukraine", region: "Europe" },
  { id: "IN", label: "India", region: "Asia-Pacific" },
  { id: "PK", label: "Pakistan", region: "Asia-Pacific" },
  { id: "BD", label: "Bangladesh", region: "Asia-Pacific" },
  { id: "CN", label: "China", region: "Asia-Pacific" },
  { id: "HK", label: "Hong Kong", region: "Asia-Pacific" },
  { id: "TW", label: "Taiwan", region: "Asia-Pacific" },
  { id: "JP", label: "Japan", region: "Asia-Pacific" },
  { id: "KR", label: "South Korea", region: "Asia-Pacific" },
  { id: "SG", label: "Singapore", region: "Asia-Pacific" },
  { id: "MY", label: "Malaysia", region: "Asia-Pacific" },
  { id: "TH", label: "Thailand", region: "Asia-Pacific" },
  { id: "ID", label: "Indonesia", region: "Asia-Pacific" },
  { id: "PH", label: "Philippines", region: "Asia-Pacific" },
  { id: "VN", label: "Vietnam", region: "Asia-Pacific" },
  { id: "AU", label: "Australia", region: "Asia-Pacific" },
  { id: "NZ", label: "New Zealand", region: "Asia-Pacific" },
  { id: "IL", label: "Israel", region: "Middle East & Africa" },
  { id: "SA", label: "Saudi Arabia", region: "Middle East & Africa" },
  { id: "AE", label: "United Arab Emirates", region: "Middle East & Africa" },
  { id: "EG", label: "Egypt", region: "Middle East & Africa" },
  { id: "NG", label: "Nigeria", region: "Middle East & Africa" },
  { id: "KE", label: "Kenya", region: "Middle East & Africa" },
  { id: "ZA", label: "South Africa", region: "Middle East & Africa" }
];

export const DEFAULT_USER_ID = "demo-user";

export function countryLabel(country: CountryCode): string {
  return COUNTRIES.find((item) => item.id === country)?.label ?? country;
}
