import type { Article, NewsStoreSnapshot, UserProfile } from "@/lib/types";
import { DEFAULT_USER_ID } from "@/lib/constants";

const now = new Date("2026-05-04T12:00:00.000Z");

function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

export const seedArticles: Article[] = [
  {
    articleId: "seed-ai-us-1",
    title: "US agencies publish new guidance for AI model audits",
    sourceId: "tech-policy-wire",
    sourceName: "Tech Policy Wire",
    sourceCountry: "US",
    url: "https://example.com/us-ai-audits",
    canonicalUrl: "https://example.com/us-ai-audits",
    publishedAt: hoursAgo(2),
    ingestedAt: hoursAgo(1),
    excerpt: "Federal agencies outlined audit expectations for high-impact AI systems used in finance, hiring, and public services.",
    summary: "US regulators are defining audit expectations for high-impact AI systems, with emphasis on risk controls and documentation.",
    topics: ["AI", "Politics", "Technology"],
    entities: ["AI regulation", "Federal agencies"],
    sentiment: "neutral",
    embedding: [0.9, 0.7, 0.2, 0.1, 0.1, 0.2],
    enriched: true,
    enrichedAt: hoursAgo(1),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-climate-gb-1",
    title: "UK grid operators accelerate offshore wind connections",
    sourceId: "energy-ledger",
    sourceName: "Energy Ledger",
    sourceCountry: "GB",
    url: "https://example.com/uk-wind-grid",
    canonicalUrl: "https://example.com/uk-wind-grid",
    publishedAt: hoursAgo(3),
    ingestedAt: hoursAgo(2),
    excerpt: "Grid operators are shortening connection timelines for offshore wind projects after a new planning framework.",
    summary: "The UK is accelerating offshore wind grid connections under a new planning process aimed at reducing energy bottlenecks.",
    topics: ["Climate", "Business"],
    entities: ["offshore wind", "UK grid"],
    sentiment: "positive",
    embedding: [0.1, 0.2, 0.9, 0.8, 0.2, 0.1],
    enriched: true,
    enrichedAt: hoursAgo(2),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-business-in-1",
    title: "Indian startups expand semiconductor design hiring",
    sourceId: "market-brief",
    sourceName: "Market Brief",
    sourceCountry: "IN",
    url: "https://example.com/india-semiconductor-hiring",
    canonicalUrl: "https://example.com/india-semiconductor-hiring",
    publishedAt: hoursAgo(4),
    ingestedAt: hoursAgo(3),
    excerpt: "Chip design firms in Bengaluru and Hyderabad are increasing hiring as global customers diversify engineering teams.",
    summary: "Indian semiconductor design startups are hiring aggressively as global demand for distributed chip engineering rises.",
    topics: ["Business", "Technology"],
    entities: ["semiconductors", "Bengaluru", "Hyderabad"],
    sentiment: "positive",
    embedding: [0.4, 0.5, 0.2, 0.2, 0.8, 0.4],
    enriched: true,
    enrichedAt: hoursAgo(3),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-health-ca-1",
    title: "Canadian hospitals test AI-assisted triage for emergency rooms",
    sourceId: "health-signal",
    sourceName: "Health Signal",
    sourceCountry: "CA",
    url: "https://example.com/canada-ai-triage",
    canonicalUrl: "https://example.com/canada-ai-triage",
    publishedAt: hoursAgo(5),
    ingestedAt: hoursAgo(4),
    excerpt: "Pilot programs are measuring whether AI tools can reduce wait times without introducing new clinical risk.",
    summary: "Canadian hospitals are piloting AI-assisted emergency triage while tracking safety, wait time, and clinician oversight.",
    topics: ["Health", "AI"],
    entities: ["emergency rooms", "AI triage"],
    sentiment: "mixed",
    embedding: [0.8, 0.6, 0.1, 0.5, 0.2, 0.2],
    enriched: true,
    enrichedAt: hoursAgo(4),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-science-jp-1",
    title: "Japanese research team reports battery density milestone",
    sourceId: "science-daily-brief",
    sourceName: "Science Daily Brief",
    sourceCountry: "JP",
    url: "https://example.com/japan-battery-density",
    canonicalUrl: "https://example.com/japan-battery-density",
    publishedAt: hoursAgo(8),
    ingestedAt: hoursAgo(7),
    excerpt: "A university-led team reported improvements in solid-state battery density after changing electrolyte materials.",
    summary: "Japanese researchers reported a solid-state battery density milestone that could matter for electric vehicles and storage.",
    topics: ["Science", "Climate", "Technology"],
    entities: ["solid-state batteries", "electric vehicles"],
    sentiment: "positive",
    embedding: [0.2, 0.4, 0.7, 0.9, 0.6, 0.1],
    enriched: true,
    enrichedAt: hoursAgo(7),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-politics-fr-1",
    title: "France debates procurement rules for public-sector AI",
    sourceId: "europe-policy-review",
    sourceName: "Europe Policy Review",
    sourceCountry: "FR",
    url: "https://example.com/france-ai-procurement",
    canonicalUrl: "https://example.com/france-ai-procurement",
    publishedAt: hoursAgo(10),
    ingestedAt: hoursAgo(9),
    excerpt: "Lawmakers are weighing transparency requirements for government AI contracts and model evaluation reports.",
    summary: "France is debating public-sector AI procurement rules focused on transparency, auditability, and vendor accountability.",
    topics: ["Politics", "AI"],
    entities: ["public-sector AI", "France"],
    sentiment: "neutral",
    embedding: [0.85, 0.75, 0.2, 0.1, 0.2, 0.3],
    enriched: true,
    enrichedAt: hoursAgo(9),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-climate-au-1",
    title: "Australia expands climate resilience funding for coastal towns",
    sourceId: "southern-climate",
    sourceName: "Southern Climate",
    sourceCountry: "AU",
    url: "https://example.com/australia-coastal-resilience",
    canonicalUrl: "https://example.com/australia-coastal-resilience",
    publishedAt: hoursAgo(12),
    ingestedAt: hoursAgo(11),
    excerpt: "New grants will fund flood mapping, resilient infrastructure, and relocation planning in vulnerable coastal communities.",
    summary: "Australia is expanding climate resilience grants for coastal towns facing flooding, erosion, and infrastructure risk.",
    topics: ["Climate", "Politics"],
    entities: ["coastal resilience", "flood mapping"],
    sentiment: "neutral",
    embedding: [0.1, 0.2, 0.95, 0.6, 0.2, 0.2],
    enriched: true,
    enrichedAt: hoursAgo(11),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-business-de-1",
    title: "German manufacturers invest in factory automation upgrades",
    sourceId: "industry-ledger",
    sourceName: "Industry Ledger",
    sourceCountry: "DE",
    url: "https://example.com/germany-factory-automation",
    canonicalUrl: "https://example.com/germany-factory-automation",
    publishedAt: hoursAgo(18),
    ingestedAt: hoursAgo(17),
    excerpt: "Mid-sized manufacturers are adding robotics and forecasting tools to offset labor shortages and energy volatility.",
    summary: "German manufacturers are investing in automation to improve productivity and adapt to labor and energy constraints.",
    topics: ["Business", "Technology"],
    entities: ["factory automation", "robotics"],
    sentiment: "positive",
    embedding: [0.3, 0.4, 0.2, 0.1, 0.85, 0.5],
    enriched: true,
    enrichedAt: hoursAgo(17),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-global-ai-1",
    title: "Global AI safety summit sets shared evaluation agenda",
    sourceId: "global-affairs-desk",
    sourceName: "Global Affairs Desk",
    sourceCountry: "GLOBAL",
    url: "https://example.com/global-ai-safety-agenda",
    canonicalUrl: "https://example.com/global-ai-safety-agenda",
    publishedAt: hoursAgo(6),
    ingestedAt: hoursAgo(5),
    excerpt: "Delegates agreed to exchange model evaluation practices but left enforcement details to national regulators.",
    summary: "A global AI safety summit produced a shared evaluation agenda while leaving enforcement to individual countries.",
    topics: ["AI", "Politics", "Technology"],
    entities: ["AI safety", "model evaluation"],
    sentiment: "neutral",
    embedding: [0.88, 0.8, 0.2, 0.1, 0.3, 0.2],
    enriched: true,
    enrichedAt: hoursAgo(5),
    enrichmentAttempts: 1
  },
  {
    articleId: "seed-sports-us-1",
    title: "US sports leagues test personalized highlight packages",
    sourceId: "sports-tech-review",
    sourceName: "Sports Tech Review",
    sourceCountry: "US",
    url: "https://example.com/us-sports-highlights",
    canonicalUrl: "https://example.com/us-sports-highlights",
    publishedAt: hoursAgo(14),
    ingestedAt: hoursAgo(13),
    excerpt: "Leagues are experimenting with AI-generated highlight reels tuned to fan preferences and local teams.",
    summary: "US sports leagues are testing AI-generated highlight packages that adapt to fan preferences and teams.",
    topics: ["Sports", "AI", "Technology"],
    entities: ["sports highlights", "fan personalization"],
    sentiment: "positive",
    embedding: [0.65, 0.5, 0.1, 0.1, 0.4, 0.9],
    enriched: true,
    enrichedAt: hoursAgo(13),
    enrichmentAttempts: 1
  }
];

export const defaultProfile: UserProfile = {
  userId: DEFAULT_USER_ID,
  selectedTopics: ["AI", "Climate"],
  selectedCountries: ["US", "GB", "GLOBAL"],
  followedEntities: [],
  mutedTopics: [],
  hiddenSources: [],
  onboardedAt: now.toISOString(),
  lastActiveAt: now.toISOString()
};

export const seedSnapshot: NewsStoreSnapshot = {
  articles: seedArticles,
  profiles: [defaultProfile],
  interactions: [],
  recommendationScores: []
};
